services:
  strapi:
    build: .
    container_name: strapi
    env_file:
      - .env
    volumes:
      - ./backend:/srv/app
      - ./data/uploads:/srv/app/public/uploads
      - ./data:/srv/app/data
    ports:
      - "1337:1337"
    networks:
      - app-network

networks:
  app-network:
    external: true
