services:
  strapi:
    build: .
    container_name: strapi
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/srv/app
      - ./.tmp:/srv/app/.tmp
      - ./data/uploads:/srv/app/public/uploads
    ports:
      - "1337:1337"
    mem_limit: 500m
    cpus: 0.8
    networks:
      - app-network

networks:
  app-network:
    external: true
